/** IPC channel names. Kept apart from ipc.ts so the preload script does not bundle zod. */
export const CHANNELS = {
  appInfo: "app:info",
  session: "auth:session",
  signIn: "auth:sign-in",
  register: "auth:register",
  refreshLicense: "auth:refresh-license",
  signOut: "auth:sign-out",
  listCompanies: "companies:list",
  pickFolder: "companies:pick-folder",
  testConnection: "companies:test",
  addCompany: "companies:add",
  checkStatus: "companies:check",
  removeCompany: "companies:remove",
  updateExtension: "companies:update-extension",
  assistantEnable: "assistant:enable",
  assistantSend: "assistant:send",
  assistantStop: "assistant:stop",
  assistantReset: "assistant:reset",
  assistantDecide: "assistant:decide",
  assistantChats: "assistant:chats",
  assistantOpenChat: "assistant:open-chat",
  assistantDeleteChat: "assistant:delete-chat",
  assistantAudit: "assistant:audit",
  assistantExportAudit: "assistant:export-audit",
  updateState: "update:state",
  updateCheck: "update:check",
  updateInstall: "update:install",
  /** main → renderer */
  assistantEvent: "assistant:event",
  updateChanged: "update:changed",
} as const;
